/**
 * Authored pixel art + per-archetype sheet builder for the GasView visual
 * agents plugin (split out of scripts/sprites/generate.mjs for the push-size
 * cap; generated output is byte-identical).
 *
 * STABLE INTERFACE consumed by scripts/sprites/generate.mjs:
 *   export function sheets(): Array<{ file: string, exports: [string, object][] }>
 * Each entry names one output file under
 * packages/client-ui-agent-team-visual/src/assets/sprites/ and the
 * [exportName, SpriteSheetData] pairs serialized into it. Sheet data uses the
 * legend below ('.' transparent, X ink, w darkWood, m muted, b brass,
 * z bronze, c copper, s steel, r oxide, h highlight, p parchment,
 * P surface, t tint slot).
 */

// lead (64x64, fps 6): fox-INSPIRED overseer — copper fur, parchment muzzle/ears,
//   brass top hat with bronze band, brass pocket watch with steel chain, tint
//   waistcoat, oxide belt, darkwood boots, curled tail. Idle: chest breathing +
//   one blink frame. Work: parchment clipboard with ink clip, bare writing
//   forearm alternating up/down the board.
// lead walk (64x64, fps 6): same leg/bob scheme as the teammate walk, plus a
//   tail sway — the parchment tail tip shifts 1px right/left on the two bob
//   frames.

const LEGEND = {
  '.': null, X: 'ink', w: 'darkWood', m: 'muted', b: 'brass', z: 'bronze',
  c: 'copper', s: 'steel', r: 'oxide', h: 'highlight', p: 'parchment',
  P: 'surface', t: 'copper',
}

// ---------------------------------------------------------------------------
// Authored pixel maps (the art lives here).
// ---------------------------------------------------------------------------

const LEAD_IDLE = [
  [
    '................................................................',
    '.........................XXXXXXXXXXXXXX.........................',
    '........................XhhbbbbbbbbbbbbX........................',
    '...................XX...XhbbbbbbbbbbbbbX...XX...................',
    '..................XhcX..XbbbbbbbbbbbbbbX..XccX..................',
    '.................XhcccX.XbbbbbbbbbbbbbbX.XcccX..................',
    '.................XccccX.XbbbbbbbbbbbbbbX.XccccX.................',
    '.................XcppccXXbbbbbbbbbbbbbbXXccppcX.................',
    '.................XcpppcXXzzzzzzzzzzzzzzXXcpppcX.................',
    '................XcppppccXzzzzzzzzzzzzzzXccppppcX................',
    '................XcpppppcXzzzzzzzzzzzzzzXcpppppcX................',
    '................XcpphppcbbbbbbbbbbbbbbbbcpppppcX................',
    '...............XcppppppccbbbbbbbbbbbbbbccppppppcX...............',
    '...............XcppppppccXXXXXXXXXXXXXXccppppppcX...............',
    '...............XccccccccccccccccccccccccccccccccX...............',
    '................XccccccccccccccccccccccccccccccX................',
    '................XccccccccccccccccccccccccccccccX................',
    '................XccccccccccccccccccccccccccccccX................',
    '................XccccccccccccccccccccccccccccccX................',
    '................XccccccccccccccccccccccccccccccX................',
    '................XccccccccccccccccccccccccccccccX................',
    '................XcccccccchccccccccccchcccccccccX................',
    '................XccccccccXXccccccccccXXccccccccX................',
    '................XccccccccXXccccccccccXXccccccccX................',
    '................XccccccccXXccccccccccXXccccmmccX................',
    '................XccccccccccccccccccccccccccmmccX................',
    '................XccccccccccccccccccccccccccmmccX................',
    '................XccccccccppppXXXXXXppppccccmmccX................',
    '................XccccccccppppXXXXXXppppccccmmccX................',
    '.................XcccccccppppXXXXXXppppccccmmcX.................',
    '.................XcccccccppppppppppppppccccmmcX.................',
    '.................XcccccccppppppppppppppcccccccX.................',
    '..................XccccccppppppXXppppppccccccX..................',
    '..................XccccccpppppXppXpppppccmmccX..................',
    '..................XcccccccppppppppppppcccmmccX..................',
    '...................XXcccccppppppppppppcccccXX...................',
    '....................XcccccccppppppppcccccccX....................',
    '....................XccccccccccccccccccccccX....................',
    '...............XXXXXtttttpppPPPPPPPPppptttttXXXXX...............',
    '..............XhtttttttttpppPPPPPPPPpppttttttttttX..............',
    '..............XttttttttttttPPPPPPPPPPtttttmmtttttX..............',
    '..............XttttttttttttPPPPXPPPPPtttttmmtttttX........X.....',
    '..............XttttttttttttPPPPPPPPPstttttmmtttttX......XXpX....',
    '..............XttttttttttttPPPPPPPPPPsstttmmtttttX.....XppppX...',
    '..............XttttttttttttPPPPXPPPPPsstttmmtttttX....XXppppX...',
    '..............XttttttttttttPPPPPPPPPPtzzzzmmtttttX...XccppppX...',
    '..............XttttttttttttPPPPPPPPPPtbbbbmmtttttX...XccppppX...',
    '..............XttttttttttttPPPPXPPPPPtbbbbmmtttttXXXXXccppppX...',
    '..............XttttttttttttPPPPPPPPPPtzbbzmmtttttXcccccccccX....',
    '..............XccccctttttttPPPPPPPPPPtttttmmcccccXcccccccccX....',
    '..............XccccctttttttPPPPPPPPPPtttttttcccccXccccccccX.....',
    '..............XcccccrrrrrrrrrrzzzzrrrrrrrrrrcccccXccccccccX.....',
    '..............XcccccrrrrrrrrrrzzzzrrrrrrrrrrccccccccccccccX.....',
    '...............XXXXXrrrrrrrrrrzzzzrrrrrrrrrrXXXcccccccccXX......',
    '....................XhmmmmmmmmXXXXmmmmmmmmmX..XcccccccccX.......',
    '....................XmmmmmmmmmX..XmmmmmmmmmX..XcccccccccX.......',
    '....................XmmmmmmmmmX..XmmmmmmmmmX..XcccccccccX.......',
    '....................XmmmmmmmmmX..XmmmmmmmmmX...XccccccXX........',
    '....................XmmmmmmmmmX..XmmmmmmmmmX...XccccccX.........',
    '...................XwwwwwwwwwwX..XwwwwwwwwwwX...XXXXXX..........',
    '...................XwwwwwwwwwwX..XwwwwwwwwwwX...................',
    '...................XwwwwwwwwwwX..XwwwwwwwwwwX...................',
    '...................XwwwwwwwwwwX..XwwwwwwwwwwX...................',
    '....................XXXXXXXXXX....XXXXXXXXXX....................',
  ],
  [
    '................................................................',
    '.........................XXXXXXXXXXXXXX.........................',
    '........................XhhbbbbbbbbbbbbX........................',
    '...................XX...XhbbbbbbbbbbbbbX...XX...................',
    '..................XhcX..XbbbbbbbbbbbbbbX..XccX..................',
    '.................XhcccX.XbbbbbbbbbbbbbbX.XcccX..................',
    '.................XccccX.XbbbbbbbbbbbbbbX.XccccX.................',
    '.................XcppccXXbbbbbbbbbbbbbbXXccppcX.................',
    '.................XcpppcXXzzzzzzzzzzzzzzXXcpppcX.................',
    '................XcppppccXzzzzzzzzzzzzzzXccppppcX................',
    '................XcpppppcXzzzzzzzzzzzzzzXcpppppcX................',
    '................XcpphppcbbbbbbbbbbbbbbbbcpppppcX................',
    '...............XcppppppccbbbbbbbbbbbbbbccppppppcX...............',
    '...............XcppppppccXXXXXXXXXXXXXXccppppppcX...............',
    '...............XccccccccccccccccccccccccccccccccX...............',
    '................XccccccccccccccccccccccccccccccX................',
    '................XccccccccccccccccccccccccccccccX................',
    '................XccccccccccccccccccccccccccccccX................',
    '................XccccccccccccccccccccccccccccccX................',
    '................XccccccccccccccccccccccccccccccX................',
    '................XccccccccccccccccccccccccccccccX................',
    '................XcccccccchccccccccccchcccccccccX................',
    '................XccccccccXXccccccccccXXccccccccX................',
    '................XccccccccXXccccccccccXXccccccccX................',
    '................XccccccccXXccccccccccXXccccmmccX................',
    '................XccccccccccccccccccccccccccmmccX................',
    '................XccccccccccccccccccccccccccmmccX................',
    '................XccccccccppppXXXXXXppppccccmmccX................',
    '................XccccccccppppXXXXXXppppccccmmccX................',
    '.................XcccccccppppXXXXXXppppccccmmcX.................',
    '.................XcccccccppppppppppppppccccmmcX.................',
    '.................XcccccccppppppppppppppcccccccX.................',
    '..................XccccccppppppXXppppppccccccX..................',
    '..................XccccccpppppXppXpppppccmmccX..................',
    '..................XcccccccppppppppppppcccmmccX..................',
    '...................XXcccccppppppppppppcccccXX...................',
    '....................XcccccccppppppppcccccccX....................',
    '....................XccccccccccccccccccccccX....................',
    '...............XXXXXtttttpppPPPPPPPPppptttttXXXXX...............',
    '..............XhtttttttttpppPPPPPPPPpppttttttttttX..............',
    '..............XttttttttttttPPPPPPPPPPtttttmmtttttX..............',
    '..............XttttttttttttPPPPXPPPPPtttttmmtttttX........X.....',
    '..............XttttttttttttPPPPPPPPPstttttmmtttttX......XXpX....',
    '..............XttttttttttttPPPPPPPPPPsstttmmtttttX.....XppppX...',
    '..............XttttttttttttPPPPPPPPPPsstttmmtttttX.....XppppX...',
    '..............XttttttttttttPPPPXPPPPPsstttmmtttttX....XXppppX...',
    '..............XttttttttttttPPPPPPPPPPtzzzzmmtttttX...XccppppX...',
    '..............XttttttttttttPPPPPPPPPPtbbbbmmtttttX...XccppppX...',
    '..............XttttttttttttPPPPXPPPPPtbbbbmmtttttXXXXXccppppX...',
    '..............XttttttttttttPPPPPPPPPPtzbbzmmtttttXcccccccccX....',
    '..............XccccctttttttPPPPPPPPPPtttttmmcccccXcccccccccX....',
    '..............XcccccrrrrrrrrrrzzzzrrrrrrrrrrcccccXccccccccX.....',
    '..............XcccccrrrrrrrrrrzzzzrrrrrrrrrrccccccccccccccX.....',
    '...............XXXXXrrrrrrrrrrzzzzrrrrrrrrrrXXXcccccccccXX......',
    '....................XhmmmmmmmmXXXXmmmmmmmmmX..XcccccccccX.......',
    '....................XmmmmmmmmmX..XmmmmmmmmmX..XcccccccccX.......',
    '....................XmmmmmmmmmX..XmmmmmmmmmX..XcccccccccX.......',
    '....................XmmmmmmmmmX..XmmmmmmmmmX...XccccccXX........',
    '....................XmmmmmmmmmX..XmmmmmmmmmX...XccccccX.........',
    '...................XwwwwwwwwwwX..XwwwwwwwwwwX...XXXXXX..........',
    '...................XwwwwwwwwwwX..XwwwwwwwwwwX...................',
    '...................XwwwwwwwwwwX..XwwwwwwwwwwX...................',
    '...................XwwwwwwwwwwX..XwwwwwwwwwwX...................',
    '....................XXXXXXXXXX....XXXXXXXXXX....................',
  ],
  [
    '................................................................',
    '.........................XXXXXXXXXXXXXX.........................',
    '........................XhhbbbbbbbbbbbbX........................',
    '...................XX...XhbbbbbbbbbbbbbX...XX...................',
    '..................XhcX..XbbbbbbbbbbbbbbX..XccX..................',
    '.................XhcccX.XbbbbbbbbbbbbbbX.XcccX..................',
    '.................XccccX.XbbbbbbbbbbbbbbX.XccccX.................',
    '.................XcppccXXbbbbbbbbbbbbbbXXccppcX.................',
    '.................XcpppcXXzzzzzzzzzzzzzzXXcpppcX.................',
    '................XcppppccXzzzzzzzzzzzzzzXccppppcX................',
    '................XcpppppcXzzzzzzzzzzzzzzXcpppppcX................',
    '................XcpphppcbbbbbbbbbbbbbbbbcpppppcX................',
    '...............XcppppppccbbbbbbbbbbbbbbccppppppcX...............',
    '...............XcppppppccXXXXXXXXXXXXXXccppppppcX...............',
    '...............XccccccccccccccccccccccccccccccccX...............',
    '................XccccccccccccccccccccccccccccccX................',
    '................XccccccccccccccccccccccccccccccX................',
    '................XccccccccccccccccccccccccccccccX................',
    '................XccccccccccccccccccccccccccccccX................',
    '................XccccccccccccccccccccccccccccccX................',
    '................XccccccccccccccccccccccccccccccX................',
    '................XcccccccchccccccccccchcccccccccX................',
    '................XccccccccccccccccccccccccccccccX................',
    '................XccccccccXXccccccccccXXccccccccX................',
    '................XccccccccccccccccccccccccccmmccX................',
    '................XccccccccccccccccccccccccccmmccX................',
    '................XccccccccccccccccccccccccccmmccX................',
    '................XccccccccppppXXXXXXppppccccmmccX................',
    '................XccccccccppppXXXXXXppppccccmmccX................',
    '.................XcccccccppppXXXXXXppppccccmmcX.................',
    '.................XcccccccppppppppppppppccccmmcX.................',
    '.................XcccccccppppppppppppppcccccccX.................',
    '..................XccccccppppppXXppppppccccccX..................',
    '..................XccccccpppppXppXpppppccmmccX..................',
    '..................XcccccccppppppppppppcccmmccX..................',
    '...................XXcccccppppppppppppcccccXX...................',
    '....................XcccccccppppppppcccccccX....................',
    '....................XccccccccccccccccccccccX....................',
    '...............XXXXXtttttpppPPPPPPPPppptttttXXXXX...............',
    '..............XhtttttttttpppPPPPPPPPpppttttttttttX..............',
    '..............XttttttttttttPPPPPPPPPPtttttmmtttttX..............',
    '..............XttttttttttttPPPPXPPPPPtttttmmtttttX........X.....',
    '..............XttttttttttttPPPPPPPPPstttttmmtttttX......XXpX....',
    '..............XttttttttttttPPPPPPPPPPsstttmmtttttX.....XppppX...',
    '..............XttttttttttttPPPPXPPPPPsstttmmtttttX....XXppppX...',
    '..............XttttttttttttPPPPPPPPPPtzzzzmmtttttX...XccppppX...',
    '..............XttttttttttttPPPPPPPPPPtbbbbmmtttttX...XccppppX...',
    '..............XttttttttttttPPPPXPPPPPtbbbbmmtttttXXXXXccppppX...',
    '..............XttttttttttttPPPPPPPPPPtzbbzmmtttttXcccccccccX....',
    '..............XccccctttttttPPPPPPPPPPtttttmmcccccXcccccccccX....',
    '..............XccccctttttttPPPPPPPPPPtttttttcccccXccccccccX.....',
    '..............XcccccrrrrrrrrrrzzzzrrrrrrrrrrcccccXccccccccX.....',
    '..............XcccccrrrrrrrrrrzzzzrrrrrrrrrrccccccccccccccX.....',
    '...............XXXXXrrrrrrrrrrzzzzrrrrrrrrrrXXXcccccccccXX......',
    '....................XhmmmmmmmmXXXXmmmmmmmmmX..XcccccccccX.......',
    '....................XmmmmmmmmmX..XmmmmmmmmmX..XcccccccccX.......',
    '....................XmmmmmmmmmX..XmmmmmmmmmX..XcccccccccX.......',
    '....................XmmmmmmmmmX..XmmmmmmmmmX...XccccccXX........',
    '....................XmmmmmmmmmX..XmmmmmmmmmX...XccccccX.........',
    '...................XwwwwwwwwwwX..XwwwwwwwwwwX...XXXXXX..........',
    '...................XwwwwwwwwwwX..XwwwwwwwwwwX...................',
    '...................XwwwwwwwwwwX..XwwwwwwwwwwX...................',
    '...................XwwwwwwwwwwX..XwwwwwwwwwwX...................',
    '....................XXXXXXXXXX....XXXXXXXXXX....................',
  ],
  [
    '................................................................',
    '.........................XXXXXXXXXXXXXX.........................',
    '........................XhhbbbbbbbbbbbbX........................',
    '...................XX...XhbbbbbbbbbbbbbX...XX...................',
    '..................XhcX..XbbbbbbbbbbbbbbX..XccX..................',
    '.................XhcccX.XbbbbbbbbbbbbbbX.XcccX..................',
    '.................XccccX.XbbbbbbbbbbbbbbX.XccccX.................',
    '.................XcppccXXbbbbbbbbbbbbbbXXccppcX.................',
    '.................XcpppcXXzzzzzzzzzzzzzzXXcpppcX.................',
    '................XcppppccXzzzzzzzzzzzzzzXccppppcX................',
    '................XcpppppcXzzzzzzzzzzzzzzXcpppppcX................',
    '................XcpphppcbbbbbbbbbbbbbbbbcpppppcX................',
    '...............XcppppppccbbbbbbbbbbbbbbccppppppcX...............',
    '...............XcppppppccXXXXXXXXXXXXXXccppppppcX...............',
    '...............XccccccccccccccccccccccccccccccccX...............',
    '................XccccccccccccccccccccccccccccccX................',
    '................XccccccccccccccccccccccccccccccX................',
    '................XccccccccccccccccccccccccccccccX................',
    '................XccccccccccccccccccccccccccccccX................',
    '................XccccccccccccccccccccccccccccccX................',
    '................XccccccccccccccccccccccccccccccX................',
    '................XcccccccchccccccccccchcccccccccX................',
    '................XccccccccXXccccccccccXXccccccccX................',
    '................XccccccccXXccccccccccXXccccccccX................',
    '................XccccccccXXccccccccccXXccccmmccX................',
    '................XccccccccccccccccccccccccccmmccX................',
    '................XccccccccccccccccccccccccccmmccX................',
    '................XccccccccppppXXXXXXppppccccmmccX................',
    '................XccccccccppppXXXXXXppppccccmmccX................',
    '.................XcccccccppppXXXXXXppppccccmmcX.................',
    '.................XcccccccppppppppppppppccccmmcX.................',
    '.................XcccccccppppppppppppppcccccccX.................',
    '..................XccccccppppppXXppppppccccccX..................',
    '..................XccccccpppppXppXpppppccmmccX..................',
    '..................XcccccccppppppppppppcccmmccX..................',
    '...................XXcccccppppppppppppcccccXX...................',
    '....................XcccccccppppppppcccccccX....................',
    '....................XccccccccccccccccccccccX....................',
    '...............XXXXXtttttpppPPPPPPPPppptttttXXXXX...............',
    '..............XhtttttttttpppPPPPPPPPpppttttttttttX..............',
    '..............XttttttttttttPPPPPPPPPPtttttmmtttttX..............',
    '..............XttttttttttttPPPPXPPPPPtttttmmtttttX........X.....',
    '..............XttttttttttttPPPPPPPPPstttttmmtttttX......XXpX....',
    '..............XttttttttttttPPPPPPPPPPsstttmmtttttX.....XppppX...',
    '..............XttttttttttttPPPPXPPPPPsstttmmtttttX....XXppppX...',
    '..............XttttttttttttPPPPPPPPPPsstttmmtttttX..m.XXppppX...',
    '..............XttttttttttttPPPPPPPPPPtzzzzmmtttttX..mXccppppX...',
    '..............XttttttttttttPPPPPPPPPPtbbbbmmtttttX...XccppppX...',
    '..............XttttttttttttPPPPXPPPPPtbbbbmmtttttXXXXXccppppX...',
    '..............XttttttttttttPPPPPPPPPPtzbbzmmtttttXcccccccccX....',
    '..............XccccctttttttPPPPPPPPPPtttttmmcccccXcccccccccX....',
    '..............XcccccrrrrrrrrrrzzzzrrrrrrrrrrcccccXccccccccX.....',
    '..............XcccccrrrrrrrrrrzzzzrrrrrrrrrrccccccccccccccX.....',
    '...............XXXXXrrrrrrrrrrzzzzrrrrrrrrrrXXXcccccccccXX......',
    '....................XhmmmmmmmmXXXXmmmmmmmmmX..XcccccccccX.......',
    '....................XmmmmmmmmmX..XmmmmmmmmmX..XcccccccccX.......',
    '....................XmmmmmmmmmX..XmmmmmmmmmX..XcccccccccX.......',
    '....................XmmmmmmmmmX..XmmmmmmmmmX...XccccccXX........',
    '....................XmmmmmmmmmX..XmmmmmmmmmX...XccccccX.........',
    '...................XwwwwwwwwwwX..XwwwwwwwwwwX...XXXXXX..........',
    '...................XwwwwwwwwwwX..XwwwwwwwwwwX...................',
    '...................XwwwwwwwwwwX..XwwwwwwwwwwX...................',
    '...................XwwwwwwwwwwX..XwwwwwwwwwwX...................',
    '....................XXXXXXXXXX....XXXXXXXXXX....................',
  ],
]

const LEAD_WORK = [
  [
    '................................................................',
    '.........................XXXXXXXXXXXXXX.........................',
    '........................XhhbbbbbbbbbbbbX........................',
    '...................XX...XhbbbbbbbbbbbbbX...XX...................',
    '..................XhcX..XbbbbbbbbbbbbbbX..XccX..................',
    '.................XhcccX.XbbbbbbbbbbbbbbX.XcccX..................',
    '.................XccccX.XbbbbbbbbbbbbbbX.XccccX.................',
    '.................XcppccXXbbbbbbbbbbbbbbXXccppcX.................',
    '.................XcpppcXXzzzzzzzzzzzzzzXXcpppcX.................',
    '................XcppppccXzzzzzzzzzzzzzzXccppppcX................',
    '................XcpppppcXzzzzzzzzzzzzzzXcpppppcX................',
    '................XcpphppcbbbbbbbbbbbbbbbbcpppppcX................',
    '...............XcppppppccbbbbbbbbbbbbbbccppppppcX...............',
    '...............XcppppppccXXXXXXXXXXXXXXccppppppcX...............',
    '...............XccccccccccccccccccccccccccccccccX...............',
    '................XccccccccccccccccccccccccccccccX................',
    '................XccccccccccccccccccccccccccccccX................',
    '................XccccccccccccccccccccccccccccccX................',
    '................XccccccccccccccccccccccccccccccX................',
    '................XccccccccccccccccccccccccccccccX................',
    '................XccccccccccccccccccccccccccccccX................',
    '................XcccccccchccccccccccchcccccccccX................',
    '................XccccccccXXccccccccccXXccccccccX................',
    '................XccccccccXXccccccccccXXccccccccX................',
    '................XccccccccXXccccccccccXXccccmmccX................',
    '................XccccccccccccccccccccccccccmmccX................',
    '................XccccccccccccccccccccccccccmmccX................',
    '................XccccccccppppXXXXXXppppccccmmccX................',
    '................XccccccccppppXXXXXXppppccccmmccX................',
    '.................XcccccccppppXXXXXXppppccccmmcX.................',
    '.................XcccccccppppppppppppppccccmmcX.................',
    '.................XcccccccppppppppppppppcccccccX.................',
    '..................XccccccppppppXXppppppccccccX..................',
    '..................XccccccpppppXppXpppppccmmccX..................',
    '..................XcccccccppppppppppppcccmmccX..................',
    '...................XXcccccppppppppppppcccccXX...................',
    '....................XcccccccppppppppcccccccX....................',
    '....................XccccccccccccccccccccccX....................',
    '.............XXXXXXXtttttpppPPPPPPPPppptttttXXXXX...............',
    '.............XbbX..XtttttpppPPPPPPPPppptttttXXXX................',
    '........XXXXXXXXXXXXXXtttttPPPPPPPPPPtttttttttttX...............',
    '........XpppptttttcccctttttPPPPXPPPPPtttttttttttX.........X.....',
    '........XpppptttttccccccccccccccccccccttttttttttX.......XXpX....',
    '........XpppptttttccccccccccccccccccccttttttttttX......XppppX...',
    '.......XccccctttttcccctttttPPPPXPPPPPsstttttttttX.....XXppppX...',
    '.......XcccccXXXXppXpXtttttPPPPPPPPPPtzzztttttttX....XccppppX...',
    '.......XcccccppppppXpXtttttPPPPPPPPPPtbbbtttttttX....XccppppX...',
    '.......XcccccppppppXpXtttttPPPPXPPPPPtbbbbmmXXXX...XXXccppppX...',
    '........XppXXXXXpppppXtttttPPPPPPPPPPtzbbzmmX.....XccccccccX....',
    '........XppppppppppppXtttttPPPPPPPPPPtttttmmX.....XccccccccX....',
    '........XppppppppppppXtttttPPPPPPPPPPtttttttX.....XcccccccX.....',
    '........XppXXXXXXppppXrrrrrrrrzzzzrrrrrrrrrrX.....XcccccccX.....',
    '........XppppppppppppXrrrrrrrrzzzzrrrrrrrrrrX.....XcccccccX.....',
    '........XppppppppppppXrrrrrrrrzzzzrrrrrrrrrrX..XXXXcccccXX......',
    '........XppXXXXXpppppXmmmmmmmmXXXXmmmmmmmmmX..XcccccccccX.......',
    '........XppppppppppppXmmmmmmmmX..XmmmmmmmmmX..XcccccccccX.......',
    '........XXXXXXXXXXXXXXmmmmmmmmX..XmmmmmmmmmX..XcccccccccX.......',
    '....................XmmmmmmmmmX..XmmmmmmmmmX...XccccccXX........',
    '....................XmmmmmmmmmX..XmmmmmmmmmX...XccccccX.........',
    '...................XwwwwwwwwwwX..XwwwwwwwwwwX...XXXXXX..........',
    '...................XwwwwwwwwwwX..XwwwwwwwwwwX...................',
    '...................XwwwwwwwwwwX..XwwwwwwwwwwX...................',
    '...................XwwwwwwwwwwX..XwwwwwwwwwwX...................',
    '....................XXXXXXXXXX....XXXXXXXXXX....................',
  ],
  [
    '................................................................',
    '.........................XXXXXXXXXXXXXX.........................',
    '........................XhhbbbbbbbbbbbbX........................',
    '...................XX...XhbbbbbbbbbbbbbX...XX...................',
    '..................XhcX..XbbbbbbbbbbbbbbX..XccX..................',
    '.................XhcccX.XbbbbbbbbbbbbbbX.XcccX..................',
    '.................XccccX.XbbbbbbbbbbbbbbX.XccccX.................',
    '.................XcppccXXbbbbbbbbbbbbbbXXccppcX.................',
    '.................XcpppcXXzzzzzzzzzzzzzzXXcpppcX.................',
    '................XcppppccXzzzzzzzzzzzzzzXccppppcX................',
    '................XcpppppcXzzzzzzzzzzzzzzXcpppppcX................',
    '................XcpphppcbbbbbbbbbbbbbbbbcpppppcX................',
    '...............XcppppppccbbbbbbbbbbbbbbccppppppcX...............',
    '...............XcppppppccXXXXXXXXXXXXXXccppppppcX...............',
    '...............XccccccccccccccccccccccccccccccccX...............',
    '................XccccccccccccccccccccccccccccccX................',
    '................XccccccccccccccccccccccccccccccX................',
    '................XccccccccccccccccccccccccccccccX................',
    '................XccccccccccccccccccccccccccccccX................',
    '................XccccccccccccccccccccccccccccccX................',
    '................XccccccccccccccccccccccccccccccX................',
    '................XcccccccchccccccccccchcccccccccX................',
    '................XccccccccXXccccccccccXXccccccccX................',
    '................XccccccccXXccccccccccXXccccccccX................',
    '................XccccccccXXccccccccccXXccccmmccX................',
    '................XccccccccccccccccccccccccccmmccX................',
    '................XccccccccccccccccccccccccccmmccX................',
    '................XccccccccppppXXXXXXppppccccmmccX................',
    '................XccccccccppppXXXXXXppppccccmmccX................',
    '.................XcccccccppppXXXXXXppppccccmmcX.................',
    '.................XcccccccppppppppppppppccccmmcX.................',
    '.................XcccccccppppppppppppppcccccccX.................',
    '..................XccccccppppppXXppppppccccccX..................',
    '..................XccccccpppppXppXpppppccmmccX..................',
    '..................XcccccccppppppppppppcccmmccX..................',
    '...................XXcccccppppppppppppcccccXX...................',
    '....................XcccccccppppppppcccccccX....................',
    '....................XccccccccccccccccccccccX....................',
    '.............XXXXXXXtttttpppPPPPPPPPppptttttXXXXX...............',
    '.............XbbX..XtttttpppPPPPPPPPppptttttXXXX................',
    '........XXXXXXXXXXXXXXtttttPPPPPPPPPPtttttttttttX...............',
    '........XppppttttttppXtttttPPPPXPPPPPtttttttttttX.........X.....',
    '........XppppttttttppXtttttPPPPPPPPPstttttttttttX.......XXpX....',
    '........XppppttttttppXtttttPPPPPPPPPPsstttttttttX......XppppX...',
    '.......XcccccttttttppXtttttPPPPXPPPPPsstttttttttX.....XXppppX...',
    '.......XcccccXXXXpcccctttttPPPPPPPPPPtzzztttttttX....XccppppX...',
    '.......XcccccpppppccccccccccccccccccccttttttttttX....XccppppX...',
    '.......XcccccpppppccccccccccccccccccccttttmmXXXX...XXXccppppX...',
    '........XppXXXXXppcccctttttPPPPPPPPPPtzbbzmmX.....XccccccccX....',
    '........XppppppppppXpXtttttPPPPPPPPPPtttttmmX.....XccccccccX....',
    '........XppppppppppXpXtttttPPPPPPPPPPtttttttX.....XcccccccX.....',
    '........XppXXXXXXppXpXrrrrrrrrzzzzrrrrrrrrrrX.....XcccccccX.....',
    '........XppppppppppppXrrrrrrrrzzzzrrrrrrrrrrX.....XcccccccX.....',
    '........XppppppppppppXrrrrrrrrzzzzrrrrrrrrrrX..XXXXcccccXX......',
    '........XppXXXXXpppppXmmmmmmmmXXXXmmmmmmmmmX..XcccccccccX.......',
    '........XppppppppppppXmmmmmmmmX..XmmmmmmmmmX..XcccccccccX.......',
    '........XXXXXXXXXXXXXXmmmmmmmmX..XmmmmmmmmmX..XcccccccccX.......',
    '....................XmmmmmmmmmX..XmmmmmmmmmX...XccccccXX........',
    '....................XmmmmmmmmmX..XmmmmmmmmmX...XccccccX.........',
    '...................XwwwwwwwwwwX..XwwwwwwwwwwX...XXXXXX..........',
    '...................XwwwwwwwwwwX..XwwwwwwwwwwX...................',
    '...................XwwwwwwwwwwX..XwwwwwwwwwwX...................',
    '...................XwwwwwwwwwwX..XwwwwwwwwwwX...................',
    '....................XXXXXXXXXX....XXXXXXXXXX....................',
  ],
  [
    '................................................................',
    '.........................XXXXXXXXXXXXXX.........................',
    '........................XhhbbbbbbbbbbbbX........................',
    '...................XX...XhbbbbbbbbbbbbbX...XX...................',
    '..................XhcX..XbbbbbbbbbbbbbbX..XccX..................',
    '.................XhcccX.XbbbbbbbbbbbbbbX.XcccX..................',
    '.................XccccX.XbbbbbbbbbbbbbbX.XccccX.................',
    '.................XcppccXXbbbbbbbbbbbbbbXXccppcX.................',
    '.................XcpppcXXzzzzzzzzzzzzzzXXcpppcX.................',
    '................XcppppccXzzzzzzzzzzzzzzXccppppcX................',
    '................XcpppppcXzzzzzzzzzzzzzzXcpppppcX................',
    '................XcpphppcbbbbbbbbbbbbbbbbcpppppcX................',
    '...............XcppppppccbbbbbbbbbbbbbbccppppppcX...............',
    '...............XcppppppccXXXXXXXXXXXXXXccppppppcX...............',
    '...............XccccccccccccccccccccccccccccccccX...............',
    '................XccccccccccccccccccccccccccccccX................',
    '................XccccccccccccccccccccccccccccccX................',
    '................XccccccccccccccccccccccccccccccX................',
    '................XccccccccccccccccccccccccccccccX................',
    '................XccccccccccccccccccccccccccccccX................',
    '................XccccccccccccccccccccccccccccccX................',
    '................XcccccccchccccccccccchcccccccccX................',
    '................XccccccccXXccccccccccXXccccccccX................',
    '................XccccccccXXccccccccccXXccccccccX................',
    '................XccccccccXXccccccccccXXccccmmccX................',
    '................XccccccccccccccccccccccccccmmccX................',
    '................XccccccccccccccccccccccccccmmccX................',
    '................XccccccccppppXXXXXXppppccccmmccX................',
    '................XccccccccppppXXXXXXppppccccmmccX................',
    '.................XcccccccppppXXXXXXppppccccmmcX.................',
    '.................XcccccccppppppppppppppccccmmcX.................',
    '.................XcccccccppppppppppppppcccccccX.................',
    '..................XccccccppppppXXppppppccccccX..................',
    '..................XccccccpppppXppXpppppccmmccX..................',
    '..................XcccccccppppppppppppcccmmccX..................',
    '...................XXcccccppppppppppppcccccXX...................',
    '....................XcccccccppppppppcccccccX....................',
    '....................XccccccccccccccccccccccX....................',
    '.............XXXXXXXtttttpppPPPPPPPPppptttttXXXXX...............',
    '.............XbbX..XtttttpppPPPPPPPPppptttttXXXX................',
    '........XXXXXXXXXXXXXXtttttPPPPPPPPPPtttttttttttX...............',
    '........XppppttttttppXtttttPPPPXPPPPPtttttttttttX.........X.....',
    '........XppppttttttppXtttttPPPPPPPPPstttttttttttX.......XXpX....',
    '........XppppttttttppXtttttPPPPPPPPPPsstttttttttX......XppppX...',
    '.......XcccccttttttppXtttttPPPPXPPPPPsstttttttttX.....XXppppX...',
    '.......XcccccXXXXppppXtttttPPPPPPPPPPtzzztttttttX....XccppppX...',
    '.......XcccccppppppppXtttttPPPPPPPPPPtbbbtttttttX....XccppppX...',
    '.......XcccccppppppppXtttttPPPPXPPPPPtbbbbmmXXXX...XXXccppppX...',
    '........XppXXXXXpppppXtttttPPPPPPPPPPtzbbzmmX.....XccccccccX....',
    '........XpppppppppcccctttttPPPPPPPPPPtttttmmX.....XccccccccX....',
    '........XpppppppppccccccccccccccccccccttttttX.....XcccccccX.....',
    '........XppXXXXXXpccccccccccccccccccccttttrrX.....XcccccccX.....',
    '........XpppppppppccccrrrrrrrrzzzzrrrrrrrrrrX.....XcccccccX.....',
    '........XppppppppppXpXrrrrrrrrzzzzrrrrrrrrrrX..XXXXcccccXX......',
    '........XppXXXXXpppXpXmmmmmmmmXXXXmmmmmmmmmX..XcccccccccX.......',
    '........XppppppppppXpXmmmmmmmmX..XmmmmmmmmmX..XcccccccccX.......',
    '........XXXXXXXXXXXXXXmmmmmmmmX..XmmmmmmmmmX..XcccccccccX.......',
    '....................XmmmmmmmmmX..XmmmmmmmmmX...XccccccXX........',
    '....................XmmmmmmmmmX..XmmmmmmmmmX...XccccccX.........',
    '...................XwwwwwwwwwwX..XwwwwwwwwwwX...XXXXXX..........',
    '...................XwwwwwwwwwwX..XwwwwwwwwwwX...................',
    '...................XwwwwwwwwwwX..XwwwwwwwwwwX...................',
    '...................XwwwwwwwwwwX..XwwwwwwwwwwX...................',
    '....................XXXXXXXXXX....XXXXXXXXXX....................',
  ],
  [
    '................................................................',
    '.........................XXXXXXXXXXXXXX.........................',
    '........................XhhbbbbbbbbbbbbX........................',
    '...................XX...XhbbbbbbbbbbbbbX...XX...................',
    '..................XhcX..XbbbbbbbbbbbbbbX..XccX..................',
    '.................XhcccX.XbbbbbbbbbbbbbbX.XcccX..................',
    '.................XccccX.XbbbbbbbbbbbbbbX.XccccX.................',
    '.................XcppccXXbbbbbbbbbbbbbbXXccppcX.................',
    '.................XcpppcXXzzzzzzzzzzzzzzXXcpppcX.................',
    '................XcppppccXzzzzzzzzzzzzzzXccppppcX................',
    '................XcpppppcXzzzzzzzzzzzzzzXcpppppcX................',
    '................XcpphppcbbbbbbbbbbbbbbbbcpppppcX................',
    '...............XcppppppccbbbbbbbbbbbbbbccppppppcX...............',
    '...............XcppppppccXXXXXXXXXXXXXXccppppppcX...............',
    '...............XccccccccccccccccccccccccccccccccX...............',
    '................XccccccccccccccccccccccccccccccX................',
    '................XccccccccccccccccccccccccccccccX................',
    '................XccccccccccccccccccccccccccccccX................',
    '................XccccccccccccccccccccccccccccccX................',
    '................XccccccccccccccccccccccccccccccX................',
    '................XccccccccccccccccccccccccccccccX................',
    '................XcccccccchccccccccccchcccccccccX................',
    '................XccccccccXXccccccccccXXccccccccX................',
    '................XccccccccXXccccccccccXXccccccccX................',
    '................XccccccccXXccccccccccXXccccmmccX................',
    '................XccccccccccccccccccccccccccmmccX................',
    '................XccccccccccccccccccccccccccmmccX................',
    '................XccccccccppppXXXXXXppppccccmmccX................',
    '................XccccccccppppXXXXXXppppccccmmccX................',
    '.................XcccccccppppXXXXXXppppccccmmcX.................',
    '.................XcccccccppppppppppppppccccmmcX.................',
    '.................XcccccccppppppppppppppcccccccX.................',
    '..................XccccccppppppXXppppppccccccX..................',
    '..................XccccccpppppXppXpppppccmmccX..................',
    '..................XcccccccppppppppppppcccmmccX..................',
    '...................XXcccccppppppppppppcccccXX...................',
    '....................XcccccccppppppppcccccccX....................',
    '....................XccccccccccccccccccccccX....................',
    '.............XXXXXXXtttttpppPPPPPPPPppptttttXXXXX...............',
    '.............XbbX..XtttttpppPPPPPPPPppptttttXXXX................',
    '........XXXXXXXXXXXXXXtttttPPPPPPPPPPtttttttttttX...............',
    '........XppppttttttppXtttttPPPPXPPPPPtttttttttttX.........X.....',
    '........XppppttttttppXtttttPPPPPPPPPstttttttttttX.......XXpX....',
    '........XppppttttttppXtttttPPPPPPPPPPsstttttttttX......XppppX...',
    '.......XcccccttttttppXtttttPPPPXPPPPPsstttttttttX.....XXppppX...',
    '.......XcccccXXXXccccXtttttPPPPPPPPPPtzzztttttttX....XccppppX...',
    '.......XcccccppppccccXccccccccccccccccttttttttttX....XccppppX...',
    '.......XcccccppppccccXccccccccccccccccttttmmXXXX...XXXccppppX...',
    '........XppXXXXXpccccXtttttPPPPPPPPPPtzbbzmmX.....XccccccccX....',
    '........XpppppppppXppXtttttPPPPPPPPPPtttttmmX.....XccccccccX....',
    '........XpppppppppXppXtttttPPPPPPPPPPtttttttX.....XcccccccX.....',
    '........XppXXXXXXpXppXrrrrrrrrzzzzrrrrrrrrrrX.....XcccccccX.....',
    '........XppppppppppppXrrrrrrrrzzzzrrrrrrrrrrX.....XcccccccX.....',
    '........XppppppppppppXrrrrrrrrzzzzrrrrrrrrrrX..XXXXcccccXX......',
    '........XppXXXXXpppppXmmmmmmmmXXXXmmmmmmmmmX..XcccccccccX.......',
    '........XppppppppppppXmmmmmmmmX..XmmmmmmmmmX..XcccccccccX.......',
    '........XXXXXXXXXXXXXXmmmmmmmmX..XmmmmmmmmmX..XcccccccccX.......',
    '....................XmmmmmmmmmX..XmmmmmmmmmX...XccccccXX........',
    '....................XmmmmmmmmmX..XmmmmmmmmmX...XccccccX.........',
    '...................XwwwwwwwwwwX..XwwwwwwwwwwX...XXXXXX..........',
    '...................XwwwwwwwwwwX..XwwwwwwwwwwX...................',
    '...................XwwwwwwwwwwX..XwwwwwwwwwwX...................',
    '...................XwwwwwwwwwwX..XwwwwwwwwwwX...................',
    '....................XXXXXXXXXX....XXXXXXXXXX....................',
  ],
]


// ---------------------------------------------------------------------------
// Walk sheet (M2): derived from idle frame 0 via deterministic pixel
// transforms — the walk art keeps the idle head/torso and re-poses the legs.
// ---------------------------------------------------------------------------

/**
 * Shift the pixel run at columns [start, start+len) by `dx` within one row,
 * filling vacated cells with '.'. Callers must ensure the target cells are
 * transparent in the original row.
 */
function shiftSpan(row, start, len, dx) {
  const cells = row.split('')
  const span = cells.slice(start, start + len)
  for (let i = start; i < start + len; i += 1) cells[i] = '.'
  for (let i = 0; i < len; i += 1) cells[start + dx + i] = span[i]
  return cells.join('')
}

/** Return a copy of `frame` with rows [start, start+rows.length) replaced. */
function withRows(frame, start, rows) {
  return [...frame.slice(0, start), ...rows, ...frame.slice(start + rows.length)]
}

/**
 * Body bob: the whole body drops 1px while the sole row stays planted (the
 * boot row above the soles is squashed out). Used for the "legs together"
 * walk frames.
 */
function bob(frame, frameWidth) {
  return ['.'.repeat(frameWidth), ...frame.slice(0, -2), frame[frame.length - 1]]
}

/**
 * leadWalk (64x64, 4f @6fps): same leg alternation/bob scheme as the
 * teammate walk, plus a tail sway — the parchment tail-tip point pixel
 * shifts 1px right on frame 1 and 1px left on frame 3.
 */
function buildLeadWalk(base) {
  const leftForward = withRows(base, 54, [
    shiftSpan(base[54], 20, 11, -1), // 'XhmmmmmmmmX' left leg top
    shiftSpan(base[55], 20, 11, -1), // 'XmmmmmmmmmX' left leg
    shiftSpan(base[56], 20, 11, -1),
    shiftSpan(base[57], 20, 11, -1),
    shiftSpan(base[58], 20, 11, -1),
    shiftSpan(base[59], 19, 12, -1), // 'XwwwwwwwwwwX' left boot
    shiftSpan(base[60], 19, 12, -1),
    shiftSpan(base[61], 19, 12, -1),
    shiftSpan(base[62], 19, 12, -1),
    shiftSpan(base[63], 20, 10, -1), // left sole
  ])
  const rightForward = withRows(base, 54, [
    shiftSpan(base[54], 33, 11, 1),  // right leg top
    shiftSpan(base[55], 33, 11, 1),  // right leg
    shiftSpan(base[56], 33, 11, 1),
    shiftSpan(base[57], 33, 11, 1),
    shiftSpan(base[58], 33, 11, 1),
    shiftSpan(base[59], 33, 12, 1),  // right boot
    shiftSpan(base[60], 33, 12, 1),
    shiftSpan(base[61], 33, 12, 1),
    shiftSpan(base[62], 33, 12, 1),
    shiftSpan(base[63], 34, 10, 1),  // right sole
  ])
  const bobbed = bob(base, 64)
  // Tail sway: only the tip point pixel (post-bob row 42, col 58) can move —
  // the 'XXpX'/'XppppX' cluster below is boxed in by its own outline. The
  // point shifts 1px right on frame 1 and 1px left on frame 3.
  const tailRight = withRows(bobbed, 42, [shiftSpan(bobbed[42], 58, 1, 1)])
  const tailLeft = withRows(bobbed, 42, [shiftSpan(bobbed[42], 58, 1, -1)])
  return [leftForward, tailRight, rightForward, tailLeft]
}

const LEAD_WALK = buildLeadWalk(LEAD_IDLE[0])

export function sheets() {
  return [
  {
    file: 'lead.ts',
    exports: [
      ['leadIdle', { name: 'lead.idle', frameWidth: 64, frameHeight: 64, fps: 6, legend: LEGEND, frames: LEAD_IDLE }],
      ['leadWork', { name: 'lead.work', frameWidth: 64, frameHeight: 64, fps: 6, legend: LEGEND, frames: LEAD_WORK }],
      ['leadWalk', { name: 'lead.walk', frameWidth: 64, frameHeight: 64, fps: 6, legend: LEGEND, frames: LEAD_WALK }],
    ],
  },
  ]
}
