#!/usr/bin/env node
/**
 * Deterministic sprite sheet generator for the GasView visual agents plugin.
 *
 * The pixel art is authored in ./art/*.mjs (one module per archetype:
 * lead, teammate, reviewer, coordinator — see SPEC-M1 art direction).
 * This orchestrator only assembles the sheets, validates them against
 * rules.mjs, and writes the four sheet files with a deterministic
 * serialization. Re-running this script leaves the generated files
 * byte-identical.
 *
 * Art-module interface (see the header comment in each ./art/*.mjs):
 *   export function sheets(): Array<{ file: string, exports: [string, object][] }>
 * Each entry names one output file under
 * packages/client-ui-agent-team-visual/src/assets/sprites/ and the
 * [exportName, SpriteSheetData] pairs serialized into it.
 *
 * Big heads (~40-45% height), 1px ink outlines, warm top-left lamplight
 * highlight pixels.
 */
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { validateSheetRules } from './rules.mjs'
import { sheets as leadSheets } from './art/lead.mjs'
import { sheets as teammateSheets } from './art/teammate.mjs'
import { sheets as reviewerSheets } from './art/reviewer.mjs'
import { sheets as coordinatorSheets } from './art/coordinator.mjs'

// ---------------------------------------------------------------------------
// Sheet assembly, validation, and deterministic emission.
// ---------------------------------------------------------------------------

/** @type {{ file: string, exports: [string, object][] }[]} */
const SHEETS = [
  ...leadSheets(),
  ...teammateSheets(),
  ...reviewerSheets(),
  ...coordinatorSheets(),
]

const HEADER = '/** GENERATED by scripts/sprites/generate.mjs — do not edit by hand. */\n'
  + "import type { SpriteSheet } from '../../engine/sprites.ts'\n\n"

function emit(exports) {
  return HEADER + exports
    .map(([exportName, sheet]) => `export const ${exportName}: SpriteSheet =\n${JSON.stringify(sheet, null, 2)}\n`)
    .join('\n')
}

const outDir = join(dirname(fileURLToPath(import.meta.url)), '../../packages/client-ui-agent-team-visual/src/assets/sprites')

// Validate every sheet before writing anything: refuse to write invalid sheets.
let failed = false
for (const { exports } of SHEETS) {
  for (const [exportName, sheet] of exports) {
    const violations = validateSheetRules(sheet)
    if (violations.length > 0) {
      failed = true
      console.error(`✗ ${sheet.name} (${exportName}) refuses to write:`)
      for (const violation of violations) console.error(`    ${violation}`)
    }
  }
}
if (failed) {
  console.error('generate: aborted, no files written')
  process.exit(1)
}
mkdirSync(outDir, { recursive: true })
for (const { file, exports } of SHEETS) {
  writeFileSync(join(outDir, file), emit(exports))
  console.log(`wrote ${file} (${exports.map(([name]) => name).join(', ')})`)
}
console.log('generate: 15 sheets written')
